-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 08, 2023 at 12:41 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `inshield`
--

-- --------------------------------------------------------

--
-- Table structure for table `questions`
--

CREATE TABLE `questions` (
  `questionID` int(11) NOT NULL,
  `question` varchar(256) NOT NULL,
  `category` varchar(256) NOT NULL,
  `optionA` varchar(256) NOT NULL,
  `optionB` varchar(256) NOT NULL,
  `optionC` varchar(256) NOT NULL,
  `optionD` varchar(256) NOT NULL,
  `answer` varchar(256) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `questions`
--

INSERT INTO `questions` (`questionID`, `question`, `category`, `optionA`, `optionB`, `optionC`, `optionD`, `answer`) VALUES
(1, 'General Data Protection Regulation (GDPR) is defined as', '1', 'An act to revise the law relating to the main non-fatal offences against the person and to provide for connected matters', 'A set of principles and rules that regulated financial firms must follow when they: Sell financial products and services to you', 'A piece of Pan-European legislation enacted by the European Parliament and Council to considerably increase Data Subjects\' rights in terms of how their data is handled', 'An act to revise the law relating to the health and welfare of animals and their protection and identification', 'c'),
(2, 'What are the two types of data that covered by GDPR?', '1', 'Personal Data, Restricted Data', 'Personal Data, Sensitive Data', 'Quantitative Data, Confidential Data', 'Internal Data, Confidential Data', 'b'),
(3, 'Who is not protected by GDPR?', '1', 'Vivian who is a German and is living in Taiwan', 'Lily who is a Spanish and get married with an Australian', 'Jamie who is born in Ireland', 'Phil who is a Polish and is dead', 'd'),
(4, 'Why is the reason data such as political opinion considered as sensitive data?', '1', 'Because people can send out hate mail or target people for physical violence according to their political opinion', 'Because political opinion is the information that nobody wants to share publicly', 'Because we have more power to act, according to the political party that we support', 'Because people can know more about how we think if our political opinion is known by them', 'a'),
(5, 'What are the two ways that GDPR used to process the sensitive data?', '1', 'Specification, Generalization', 'Anonymization, Randomization', 'Anonymization, Pseudonymization', 'Hashing of data, Generalization', 'c'),
(6, 'What does ‘processing’ mean in GDPR?', '1', 'The marking of stored personal data with the aim of limiting their processing in the future', 'Any operation or set of operations which is performed on personal data or on sets of personal data', 'Any form of automated processing of personal data consisting of the use of personal data to evaluate certain personal aspects relating to a natural person', 'A natural or legal person, public authority, agency or other body which processes personal data on behalf of the controller', 'b'),
(7, 'What does ‘recipient’ mean in GDPR?', '1', 'A natural or legal person, public authority, agency, or other body which processes personal data on behalf of the controller', 'A natural or legal person, public authority, agency, or body other than the data subject, controller, processor, and persons who, under the direct authority of the controller or processor, are authorised to process personal data', 'A natural or legal person, public authority, agency, or another body, to which the personal data are disclosed, whether a third party or not', 'Any information relating to an identified or identifiable natural person', 'c'),
(8, 'What does ‘genetic data’ mean in GDPR?', '1', 'Personal data resulting from specific technical processing relating to the physical, physiological, or behavioural characteristics of a natural person', 'Personal data that can be freely used, reused, and redistributed by anyone with no existing local, national or international legal restrictions on access or usage', 'Personal data that cannot be freely used, reused, and redistributed by anyone with no existing local, national or international legal restrictions on access or usage', 'Personal data relating to the inherited or acquired genetic characteristics of a natural person which give unique information about the physiology or the health of that natural person', 'd'),
(9, 'What does ‘biometric data’ mean in GDPR?', '1', 'Personal data resulting from specific technical processing relating to the physical, physiological, or behavioural characteristics of a natural person', 'Personal data that can be freely used, reused, and redistributed by anyone with no existing local, national or international legal restrictions on access or usage', 'Personal data that cannot be freely used, reused, and redistributed by anyone with no existing local, national or international legal restrictions on access or usage', 'Personal data relating to the inherited or acquired genetic characteristics of a natural person which give unique information about the physiology or the health of that natural person', 'a'),
(10, 'What does ‘data concerning health’ mean in GDPR?', '1', 'Personal data resulting from specific technical processing relating to the physical, physiological, or behavioural characteristics of a natural person', 'Personal data that can be freely used, reused, and redistributed by anyone with no existing local, national or international legal restrictions on access or usage', 'Personal data related to the physical or mental health of a natural person', 'Personal data relating to the inherited or acquired genetic characteristics of a natural person which give unique information about the physiology or the health of that natural person', 'c'),
(11, 'Who is not protected by GDPR?', '2', 'Tristan, a France went browsing an online store in Singapore', 'Jimmy, a Lithuanians went online shopping in an online store in Malta', 'Abraham, a Mexican went online shopping in an online store in Morocco', 'Andrew, a British who signed up for an online fitness plan in Ireland', 'c'),
(12, 'Is the following statement true or false?  GDPR is only applied in countries from the EU', '2', 'True', 'False', 'Depends on which country it is', '–', 'b'),
(13, 'Which of the following statements is the most accurate statement about the location that GDPR apply?', '2', 'GDPR only applies in the EU', 'GDPR only applies in Ireland', 'GDPR only applies if the organization is in the EU, or the organization has EU customers', 'GDPR only applies if the organization is not in the EU but has EU customers', 'c'),
(14, 'What is the definition for extra territorial applicability in GDPR?', '2', 'Law applying alike to all persons regardless of their nationality or citizenship within a given territory', 'Law applying to the processing of EU personal data by Controllers that are not established in the EU, but in a place where Member State law applies by public international law', 'Law applying when the organization conduct business in within a certain territory', 'Law applying when the organization conduct business for people within EU and any countries that is 125km from the EU', 'b'),
(15, 'Which of the following countries is not covered by the General Data Protection Regulation (GDPR)?', '2', 'Sweden', 'France', 'Germany', 'Australia', 'd'),
(16, 'Which of the following is not a requirement for companies to be subject to the GDPR?', '2', 'Having a physical presence in the EU', 'Collecting and processing the personal data of EU citizens', 'Offering goods or services to EU citizens', 'Being incorporated in the EU', 'a'),
(17, 'If a company based in the EU processes the personal data of individuals in the United States, is the GDPR applicable to the company?', '2', 'Yes, the GDPR always applies to the processing of personal data by companies based in the EU', 'No, the GDPR only applies to the processing of personal data of EU citizens', 'Yes, if the company is offering goods or services to individuals in the EU', 'No, the GDPR only applies to the processing of personal data of individuals within the EU', 'd'),
(18, 'Can a company based outside of the EU be subject to the GDPR if it processes the personal data of individuals located within the EU, but not for the purpose of offering goods or services to those individuals?', '2', 'No, the GDPR only applies to the processing of personal data for the purpose of offering goods or services', 'Yes, the GDPR applies to all processing of personal data within the EU', 'Yes, but only if the company monitors the behaviour of the individuals', 'Yes, but only if the company processes the personal data of EU citizens', 'c'),
(19, 'Can a company based in the EU be subject to the GDPR if it processes the personal data of individuals located outside of the EU, but not for the purpose of offering goods or services to those individuals or monitoring their behaviour?', '2', 'No, the GDPR only applies to the processing of personal data for the purpose of offering goods or services or monitoring behaviour', 'Yes, the GDPR applies to all processing of personal data, regardless of location', 'Yes, but only if the company processes the personal data of EU citizens', 'Yes, but only if the company processes the personal data of non-EU citizens', 'a'),
(20, 'Is it possible for a company based outside of the EU to be subject to the GDPR?', '2', 'No, the GDPR only applies to companies within the EU', 'Yes, if the company offers goods or services to individuals in the EU', 'Yes, if the company monitors the behaviour of individuals in the EU', 'Yes, if the company processes the personal data of individuals in the EU', 'b'),
(21, 'Which of the following statement is false or not related about lawfulness in GDPR?', '3', 'Consent to process the person is given by the user', 'Personal data must be processed to fulfil a contract', 'It is required to satisfy a legal responsibility', 'It is a private task carried out in the private interest', 'd'),
(22, 'Which of the following is the true about fairness in GDPR?', '3', 'You are allowed to keep information about what or why you are collecting data on purpose', 'You are not allowed to mishandle or abuse the information collected, unless you are not a native speaker of English', 'You must be clear, open, and honest with data subjects about who you are, and why you are processing their data', 'You can demonstrate that there is a legitimate interest that is not outweighed by the rights and interests of the data subject', 'c'),
(23, 'Is the following statement complying and related to purpose limitation?  Privacy policy include a lawful basis to explain why the company needs to process personal information. The reason for data processing, eg the fulfilment of a contract is stated', '3', 'Yes', 'No', 'Yes, if the reason is related, No if it is not', '-', 'b'),
(24, 'Which of the following statement is false or not related about purpose limitation in GDPR?', '3', 'The consent to process the data should be asked again if the data collected wanted to be used for a new purpose that is incompatible with the original purpose even though there is a clear obligation or function set out in law', 'The purpose of this principle is to ensure that data is only collected for stated, explicit, and lawful purposes', 'The data processing purposes should be strictly adhered to, restricting data processing to the indicated reasons only', 'One of the purposes of this principle is to restrict the use of data for certain activities', 'a'),
(25, 'Which of the following is complying to the data minimization principle in GDPR?', '3', 'Email, phone numbers, home address of the users is collected for an email newsletter subscription', 'Users need to provide the home address for a reservation of table in a restaurant', 'Home address and phone numbers are required, microphone of the device also have to be enabled for online shopping', 'Fingerprint is collected at the entrance of a building is to prevent unauthorised persons from entering', 'd'),
(26, 'Which of the following is false or not related about the principle accuracy in GDPR?', '3', 'All personal data collected, stored, or processed by a controller must be accurate and up to date', 'Controller should take all reasonable steps to correct any inaccuracies promptly', 'The users should go and update the information themselves if any of the information on the website is changed', 'The purpose of this principle is to make sure the personal data are accurate and where needed, kept up to date', 'c'),
(27, 'Which of the following statements is true about the principle storage limitation in GDPR?', '3', 'Personal data is only allowed to be stored for longer periods when they will process solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes', 'Controllers have the choice to delete personal data as soon as it stops being needed for the purposes for which it was originally collected or keep it in the database', 'The controllers have a choice to justify how long each piece of data will be kept', 'Under GDPR, personal data in a form which permits the identification of individuals should be held no longer than necessary for the purposes unless stated', 'a'),
(28, 'Which of the following is the protection that are included in Integrity and confidentiality principle in GDPR?', '3', 'Unauthorized or unlawful processing, human-caused loss', 'Accidental destruction, unlawful processing', 'Unauthorized but lawful processing, human-caused loss', 'Damage caused by natural disaster, Authorized but unlawful processing', 'b'),
(29, 'Which of the following statements is false or not related about the accountability principle in GDPR?', '3', 'It is a new principle in GDPR', 'The organization or a person must have appropriate measures and records in place as proof of compliance with the data processing principles', 'One of the way to achieve accountability is the controller always ask the users if they wanted to update their personal information stored in the website', 'The purpose of this principle is to prevent the organization from saying that they are following all the rules without doing it', 'c'),
(30, 'Until the year of 2022, how many principles are there in total for GDPR?', '3', '6', '7', '8', '9', 'b'),
(31, 'Which articles of GDPR contains all the information that must be provided when collecting personal data?', '3', '11', '12', '13', '14', 'c'),
(32, 'Which articles of GDPR contains the responsibilities when obtaining data about the data subject from a third party or indirectly?', '3', '11', '12', '13', '14', 'd'),
(33, 'According to Article 13 of GDPR, which of the following information is not one of the information that is needed to be provided when personal data is being collected?', '3', 'The reasons and the way their personal data is being processed', 'Legal basis for processing and the purposes of the processing', 'Country where the processing of data occurs', 'Legitimate interests of the processor and third parties', 'a'),
(34, 'Which of the following statement is false or not related about the right of access in GDPR?', '3', 'The data subject or the natural person can ask specifically about their personal data file', 'The data subject or the natural person can request for as many copies of the data as they want without getting charged', 'The data subject or the natural person can ask the period that their personal data is intended to be stored', 'The data subject or the natural person can request to know any information available to the source of data when the data are not collected from the data subject', 'b'),
(35, 'Which of the following is false or not related to the right to rectification in GDPR?', '3', 'The data subjects have the right to change or modify the data they provide when the data is inaccurate or out-of-date without undue delay', 'One of the reasons holding accurate data is so important for the organization and the data subject is because incorrect data threatens the privacy of other individuals', 'The right to rectification adds an extra layer of transparency to the processing activities', 'One example of ways to comply to this right to rectification is providing the data subjects can update their information on their own time through a customer account and profile', 'c'),
(36, 'Which of the following statement is not one of the circumstances when the data subject has the right to ask a data controller to erase their data without undue delay?', '3', 'The personal data must be erased for compliance with a legal obligation in Union or Member State law to which the controller is subject', 'The personal data are no longer necessary in relation to the purposes for which they were collected or otherwise processed', 'The personal data have been unlawfully processed', 'When the personal data is in the process of being updated', 'd'),
(37, 'What happened if a data subject has the right to restriction of processing and the controller wishes to continue processing?', '3', 'The controller will receive a warning not to continue processing the data and is not allowed to continue processing the data because the data subject has the right to restriction to processing', 'The controller will be imposed a fine up to 20 million Euro or 4% of worldwide annual turnover (whichever is higher)', 'The controller needs to prove that there is a legitimate reason for continuing to process the data', 'The controller needs to show evidence that the personal data will be used for processing that is to have no effect or discloses sensitive information', 'c'),
(38, 'Which of the following is the purpose of the right to data portability?', '3', 'To enable a user to reuse their data for the purpose to transfer it to another controller', 'To avoid the controller from making any automated decisions towards their transferable personal data', 'To restrict the transfer of their personal data from controller to another controller', 'To enable a user to voice out and object when their personal data is being transferred to another controller', 'a'),
(39, 'According to Article 21 of GDPR, the data subject has the right to object to their data being processed. What happened if the objections are failed?', '3', 'The controller will not be allowed to process the data', 'The controller must still have sufficient legal grounds to continue using or processing the data', 'The data subject needs to make other objections until it is successfully objected', 'The controller will be imposed a fine up to 20 million Euro or 4% of worldwide annual turnover (whichever is higher)', 'b'),
(40, 'Which of the following is not the condition when the right to avoid automated decision-making cannot be implemented?', '3', 'When automated decision-making is needed to enter or complete a contract', 'When the control has authorization from the EU or a Member State and uses safeguards to protect the subject’s interests and freedom', 'When the profiling or decision-making occurs with the subject’s explicit consent', 'When the data subject is conducting objection to the processing of their personal data', 'd'),
(41, 'According to the General Data Protection Regulation (GDPR), when does an organisation need to take action to legitimise cross-border data transfers of personal data?', '4', 'When the data is routed through another jurisdiction, whether the other jurisdiction is in or outside the European Union', 'When the data is transferred from one jurisdiction within the European Union to another jurisdiction within the European Union', 'When the data is transferred from a jurisdiction outside the European Union to a member state of the European Union', 'When the data is transferred from a jurisdiction in the European Union to a third country which is not deemed adequate', 'd'),
(42, 'Which is an example of direct marketing?', '4', 'An email sent to an individual about an order she has placed for a book', 'An email sent to an individual promoting a new book which is on sale', 'A letter addressed to ‘the household’ about a charity bookstore', 'An advertisement on a website promoting a new book which is on sale', 'b'),
(43, 'When should a controller notify the supervisory authority of a loss of personal information which is likely to result in harm to an individual?', '4', 'Within 72 hours after the controller becomes aware of it', 'No later than 5 calendar days after the incident is identified', 'Without unreasonable delay but no later than 30 days', 'Notification to the supervisory authority is not required', 'a'),
(44, 'Under what condition is processing ‘sensitive employee data’ acceptable?', '4', 'The processing is necessary to improve the quality of the employer-employee relationship.', 'The processing is necessary for the data controller to carry out their obligation in the field of employment law', 'The processing is necessary for the interest of both the data controller and the employee.', 'The processing is necessary for the interests pursued by the data controller', 'b'),
(45, '5.	Why do binding corporate rules (BCRs) prohibit the transfer of employee names to telecom providers within the same country in order to provide them with mobile phone services?', '4', 'A.	Because BCRs only provide adequate safeguards for organisations who move data outside their corporation', 'B.	Because BCRs secure transfers to third parties without needing to fulfil additional requirements', 'C.	Because BCRs only deal with intra-organisational transfers and not with transfers to third parties', 'D.	Because BCRs require contractual arrangements to legitimize international transfers of data', 'c'),
(46, 'Under the GDPR, would a European company be allowed to use video surveillance to monitor employee access to inventory?', '4', 'No, under the GDPR, using video surveillance is never allowed', 'No, video surveillance is too intrusive a solution for inventory access.', 'Yes, provided that the company complies with specific conditions', 'Yes, without any further conditions to be taken into account', 'c'),
(47, 'Which institution is responsible for ensuring that directives are implemented properly by the member states?', '4', 'European Court of Justice', 'European Commission', 'European Parliament', 'European Data Protection Supervisor', 'b'),
(48, 'What is true for a contract based on European Commission standard contractual clauses with a processor outside the European Economic Area?', '4', 'For subcontracting, the processor must inform the controller and obtain written approval', 'Before the processing starts, the processor must obtain permission from the European Commission', 'The data subject must consent to processing by a processor located outside of the European Economic Area', 'The processor must provide a compliance statement from its data protection authority.', 'a'),
(49, 'Rob, a former employee of the Tea & Biscuits Corporation (a U.S.-based multi-national), has hand-delivered a letter to the Reception of the Irish Subsidiary on May 1. Rob asked for a copy of all data that Tea & Biscuits Corporation holds about him from the', '4', 'Meet with the legal department to ensure that no U.S. data protection laws will be violated before sending any information', 'After accounting for GDPR compliance, contact Rob ‘without undue delay’ to clarify any questions about his request.', 'Consult with a security lawyer before sending any information to determine the most secure way to fulfil the request', 'Wait for advice from the Irish Data Protection Authority before sending any information', 'b'),
(50, 'Rob, a former employee of the Tea & Biscuits Corporation (a U.S.-based multi-national), has hand-delivered a letter to the Reception of the Irish Subsidiary on May 1. Rob asked for a copy of all data that Tea & Biscuits Corporation holds about him from the', '4', 'Within a month of having received the request', 'Within six months of having received the request', 'Without undue delay or within a month of receiving the request', 'Three months after they authenticate the identity of the requestor', 'c'),
(51, 'Rob, a former employee of the Tea & Biscuits Corporation (a U.S.-based multi-national), has hand-delivered a letter to the Reception of the Irish Subsidiary on May 1. Rob asked for a copy of all data that Tea & Biscuits Corporation holds about him from the', '4', 'Nothing. Email does not need to be provided in response to a subject access request under the local Irish Data Protection law.', 'The HR manager should ask employees who still work at Tea & Biscuits if they have any email correspondence with Rob in their possession', 'Conduct an email search in accordance with its monitoring policy and inform affected employees before any disclosures to Rob', 'HR should provide Rob the information he requested. There is no need to get other employees’ consent because the emails are all work related', 'c'),
(52, 'Which is NOT a compatible purpose for processing data beyond the purpose originally specified at the time of collection?', '4', 'Performance of a contract.', 'Transferring data to an archive.', 'Statistical purposes.', 'Historical or scientific research.', 'a'),
(53, 'Along with legitimacy, what is another condition that must be met when carrying out employee monitoring?', '4', 'The monitoring must be in the public interest at the time of collection', 'The monitoring must be done during agreed-upon time constraints', 'The monitoring must be performed under an employment contract', 'The monitoring must be limited to what is necessary for the purposes', 'd'),
(54, 'Which is an example of cloud computing?', '4', 'A software package installed on a laptop', 'A web-based email platform', 'A portable mass storage device', 'A single web server', 'b'),
(55, 'According to the GDPR, the right to data portability applies:', '4', 'When processing was originally based on the user’s consent.', 'When the processing was based on a public interest', 'When the processing was done through ‘manual means’.', 'When the processing was based on the controller’s legitimate interests', 'a'),
(56, 'A collection is part of a historical research initiative. Which is the most accurate statement concerning the obligations imposed by the GDPR?', '4', 'As a regulation rather than a directive, the GDPR sets forth binding provisions for EU member states to follow without discretion', 'The GDPR provides a framework which member states can choose to use as a basis for national legislation', 'As a regulation rather than a directive, the GDPR sets forth binding provisions for EU member states to follow but it leaves them discretion in some areas.', 'The GDPR imposes binding obligations on all EU member states as well as on all countries deemed ‘adequate’ by the European Commission', 'c'),
(57, 'Which is the most accurate statement concerning the obligations imposed by the GDPR regarding notification of data processing activities?', '4', 'Notification is now optional but is recommended to foster the transparency of data processing activities.', 'Notification remains mandatory to finance the national data protection authority’s operations', 'Notification is no longer required as the GDPR has switched to an accountability framework', 'Notification is required of all processors but is not required of controllers.', 'c'),
(58, 'Which, according to the GDPR, is NOT one of the considerations that should be taken into account to determine the appropriate technical and organisational measures to ensure a level of data security appropriate to the risk?', '4', 'Costs of implementation.', 'The state of the art', 'Scope of processing', 'The size of the organisation', 'd'),
(59, 'Which is NOT a special category of data?', '4', 'Political affiliation', 'Health information', 'Ethnic origin.', 'Social Security number', 'd'),
(60, 'Which institution has the power to adopt adequacy findings for the European Union?', '4', 'Working Party 29.', 'European Commission.', 'European Data Protection Supervisor', 'European Court of Justice.', 'b'),
(61, 'Which exemption to the e-Privacy Directive 2002/58/EC allows the data controller to send electronic marketing information?', '4', 'The recipients are existing customers', 'The controller is a non-profit organisation', 'The data subject and controller work in the same industry', 'The recipient’s email address is taken from a public register', 'a'),
(62, 'Under the GDPR, organizations that are not established in the EU that monitor behaviour will be subject to the Regulation when:', '4', 'The equipment being used for monitoring is located in the EU.', 'The behaviour being monitored occurs within the EU.', 'The individual being monitored is a citizen of an EU member state.', 'The individual being monitored is an EU citizen visiting the United States.', 'b'),
(63, 'Big data projects often gather and generate a multitude of data and relations that lead to additional data derivation opportunities. Which of the following statements is correct with regard to big data?', '4', 'Big data projects are exempt from the proportionality principle of the GDPR.', 'Big data projects are subject to case-by-case review under the GDPR.', 'Big data projects are subject to the proportionality principle of the GDPR.', 'Big data projects are permitted to retain all data collected prior to the GDPR taking effect.', 'c'),
(64, 'Under the GDPR, privacy notices relating to services intended for children, must be:', '4', 'In a concise, transparent, intelligible, easily accessible form for adults to understand and explain to the child', 'In a concise, transparent, intelligible, easily accessible form and in language the child can understand.', 'In concise legal language comprehendible to a subject matter expert or legal professional.', 'In the same format as privacy notices intended for adults as children are not addressed separately under the GDPR.', 'b'),
(65, 'If a third-country data controller or processor does not wish to comply with the supervisory authority decision, then under the GDPR, the supervisory authority has the power:', '4', 'To waive its decision as its powers are limited to the EU and its member states.', 'To carry out its actions outside the EU without the target country’s consent.', 'To force the data controller or processor to relocate to an EU member state.', 'To order the suspension of data flows to a recipient in the third country.', 'd');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `questions`
--
ALTER TABLE `questions`
  ADD PRIMARY KEY (`questionID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `questions`
--
ALTER TABLE `questions`
  MODIFY `questionID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=66;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
